### ISSUE TITLE
Homepage layout：about the “Current Working On” and the “document”

### ISSUE THREAD

**Issue by hqc19907228** [beyondstorage/site#222]
1 The content of the box on the right needs to be aligned with the left.
<img width="790" alt="微信截图_20210906145223" src="https://user-images.githubusercontent.com/84710719/132180194-2bc75889-08a3-4b81-9e5d-93c220799872.png">

2 When I click the document button, the page is misaligned.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/84710719/132181003-5c107bf5-08b0-4946-877f-6f7f9cc6c0f7.png">

**Comment by Xuanwo** [comment]
@tt-haogege is working on resolving problem 2 at #216 

For problem 1, we need @queenaray928 's advice

**Comment by tt-haogege** [comment]
Problem 2 has been solved

**Comment by queenaray928** [comment]
The design draft is consistent with the description of issue 1 of this issuse. At that time, the front-end personnel did not have time to adjust, and now they need to be modified.

![image](https://user-images.githubusercontent.com/86776409/132182422-36cce982-5114-41dd-8248-6e3facede635.png)

**Comment by Xuanwo** [comment]
Should be fixed, please feel free to reopen this issue if anything wrong.
