### ISSUE TITLE
Architecture image has a typo

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/site#244]
![image](https://user-images.githubusercontent.com/5351546/135189848-b4806cd9-4ca5-4cbe-940f-7cb14a812801.png)

Shoud be `FUSE`.

**Comment by queenaray928** [comment]
The final design draft is correct, is FUSE.
Please help replace the final correct architecture image @houz42 

![Architecture](https://user-images.githubusercontent.com/86776409/135192095-75920359-e498-4bde-a735-64d85183adaf.png)

**Comment by Xuanwo** [comment]
ping @tt-haogege, can you take a look on this issue?

**Comment by tt-haogege** [comment]
done

**Comment by Xuanwo** [comment]
Fixed in https://github.com/beyondstorage/site/pull/245.

ping @tt-haogege , it cloud be better if we add more context for our replies.

For example, add our PR links here.
