### ISSUE TITLE
Unify icons for objects in storager

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/site#28]
In the graph for storager, it is better to unify icons for objects or not?

**Comment by Xuanwo** [comment]
Please provide more info in the issue, so that others can contribute.

For example, attach the page linke or screenshot here.

**Comment by Prnyself** [comment]
[https://site-git-docs-options-aos-dev.vercel.app/docs/go-storage/index](https://site-git-docs-options-aos-dev.vercel.app/docs/go-storage/index)
here is the image file: [https://github.com/aos-dev/site/blob/master/static/docs/go-storage/operations/operations.png](https://github.com/aos-dev/site/blob/master/static/docs/go-storage/operations/operations.png)
screenshot attached below:
<img width="958" alt="图片" src="https://user-images.githubusercontent.com/9412660/114835699-6cf53880-9e04-11eb-863d-7a083a8a1c8c.png">

**Comment by Xuanwo** [comment]
We will use images from our designer instead.
