### ISSUE TITLE
The link to the github icon on the official website is not working

### ISSUE THREAD

**Issue by bokket** [beyondstorage/site#82]
Originally it should go to https://github.com/aos-dev 
after the organization changed its name to Beyond Storage it should go to https://github.com/beyondstorage

I think this is a place that didn't come to mind during the discord discussion, I'm willing to do this

**Comment by Xuanwo** [comment]
I think update the `docusaurus.config.js` is enough.

**Comment by bokket** [comment]
Yes, do I need to build yarn tests locally? Might be a bit tricky.
I think if it's just an icon issue, it would only need to be changed in one place, but in fact, there are many places where https://github.com/aos-dev still exists
 This is old-fashioned link

**Comment by Xuanwo** [comment]
> Yes, do I need to build yarn tests locally? Might be a bit tricky.
> I think if it's just an icon issue, it would only need to be changed in one place, but in fact, there are many places where https://github.com/aos-dev still exists this old-fashioned link

As described in https://github.com/beyondstorage/go-storage/issues/577, we only update the links in our code-related repo. Update all links contains `aos-dev` may be a hugo burdon for us, let's update them one by one.
